### ISSUE TITLE
Is libnss_tacplus is compatible with Ubuntu 22.04

### ISSUE THREAD

**Issue by knight-on-work** [daveolson53/libnss-tacplus#2]
I just want to know that is  libnss_tacplus is compatible with Ubuntu 22.04 or not? Because I successfully install all libraries and done configuration for TACACS+ server but it is not working properly. Please help if anyone done with Ubuntu 22.04

**Comment by daveolson53** [comment]
Probably not compatible without updating.  I'm retired, and will not be working on this set of issues.

**Comment by daveolson53** [comment]
Not planned
